spring:
  influxdb:
    url: http://localhost:8086
    username: admin
    password:
    database: hhui
    retention-policy: autogen
    connect-timeout: 10
    read-timeout: 30
    write-timeout: 10
    gzip: true